version: '3.8'

networks:
  trading-net:
    driver: bridge

services:
  webhook:
    build: .
    restart: unless-stopped
    environment:
      - IB_HOST=ibgateway
      - IBC_PORT=4002
      - TRADING_ACCOUNT=${TRADING_ACCOUNT}
    networks:
      - trading-net
    depends_on:
      - ibgateway
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ibgateway:
    image: ghcr.io/gnzsnz/ib-gateway:stable
    networks:
      trading-net:
        aliases:
          - ibgateway
    ports:
      - "4002:4002"
