version: '3.8'

services:
  webhook:
    build: .
    container_name: webhook
    restart: unless-stopped
    environment:
      - IB_HOST=ibgateway              # resolves via shared network
      - IBC_PORT=${IBC_PORT:-4002}     # default to paper trading
      - TRADING_ACCOUNT=${TRADING_ACCOUNT}
    networks:
      - ibgw-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  ibgw-net:
    external: true
